SELECT t.SUBJECT_ID, t.HADM_ID, t.ITEMID, t.time, COUNT(t.VALUENUM) AS 'count', AVG(t.VALUENUM) AS 'average', MIN(t.VALUENUM) AS 'min', MAX(t.VALUENUM) AS 'max', t.VALUEUOM
FROM
(
	SELECT c.SUBJECT_ID, c.HADM_ID, TIMESTAMPDIFF(HOUR, a.ADMITTIME, c.CHARTTIME) AS 'time', c.ITEMID, c.VALUENUM, c.VALUEUOM
	FROM
	(
		(
			SELECT ADMITTIME, SUBJECT_ID, HADM_ID
			FROM ADMISSIONS
			LIMIT 100
		) a
		INNER JOIN 
		(
			SELECT SUBJECT_ID, HADM_ID, CHARTTIME, ITEMID, VALUENUM, VALUEUOM
			FROM CHARTEVENTS
			WHERE VALUENUM IS NOT NULL
		) c
		ON (a.HADM_ID = c.HADM_ID) AND (a.SUBJECT_ID = c.SUBJECT_ID)
	)
) t
GROUP BY t.SUBJECT_ID, t.HADM_ID, t.ITEMID, t.time
ORDER BY t.SUBJECT_ID, t.HADM_ID, t.ITEMID, t.time, t.VALUENUM