SELECT t.SUBJECT_ID, t.HADM_ID, t.ITEMID, t.time, t.VALUENUM, t.VALUEUOM
FROM
(
	SELECT i.SUBJECT_ID, i.HADM_ID, TIMESTAMPDIFF(HOUR, a.ADMITTIME, i.CHARTTIME) AS 'time', i.ITEMID, i.VALUENUM, i.VALUEUOM
	FROM
	(
		(
			SELECT ADMITTIME, SUBJECT_ID, HADM_ID
			FROM ADMISSIONS
			LIMIT 100
		) a
		INNER JOIN 
		(
			(
				SELECT SUBJECT_ID, HADM_ID, CHARTTIME, ITEMID, VALUENUM, VALUEUOM
				FROM CHARTEVENTS
				WHERE VALUENUM IS NOT NULL
			) c
			UNION
			(
				SELECT SUBJECT_ID, HADM_ID, CHARTTIME, ITEMID, VALUENUM, VALUEUOM
				FROM LABEVENTS
				WHERE VALUENUM IS NOT NULL
			) l
		) i
		ON (a.HADM_ID = i.HADM_ID) AND (a.SUBJECT_ID = i.SUBJECT_ID)
	)
) t
WHERE t.ITEMID=50912
ORDER BY t.SUBJECT_ID, t.HADM_ID, t.ITEMID, t.time, t.VALUENUM