CREATE TABLE TIMED_CHARTEVENTS
SELECT c.*, a.ADMITTIME AS ADMITTIME, TIMESTAMPDIFF(HOUR, a.ADMITTIME, c.STORETIME) AS 'time'
FROM
(
	(
		SELECT *
		FROM `FILTERED_ADMISSIONS`
	) a
	INNER JOIN
	(
		SELECT *
		FROM `FILTERED_CHARTEVENTS`
		WHERE VALUENUM IS NOT NULL
	) c
	ON (a.HADM_ID = c.HADM_ID) AND (a.SUBJECT_ID = c.SUBJECT_ID)
)
ORDER BY time

CREATE TABLE AVG_TIMED_CHARTEVENTS
SELECT SUBJECT_ID, HADM_ID, ITEMID, time, COUNT(VALUENUM) AS 'count', AVG(VALUENUM) AS 'average', MIN(VALUENUM) AS 'min', MAX(VALUENUM) AS 'max', VALUEUOM
FROM
TIMED_CHARTEVENTS
GROUP BY SUBJECT_ID, HADM_ID, ITEMID, time

-- for TIMED_CHARTEVENTS (202,501,134 rows) and TIMED_LABEVENTS (20,671,577 rows)

CREATE TABLE TIMED_LABEVENTS
SELECT c.*, a.ADMITTIME AS ADMITTIME, TIMESTAMPDIFF(HOUR, a.ADMITTIME, c.CHARTTIME) AS 'time'
FROM
(
	(
		SELECT *
		FROM `FILTERED_ADMISSIONS`
	) a
	INNER JOIN
	(
		SELECT *
		FROM `FILTERED_LABEVENTS`
		WHERE VALUENUM IS NOT NULL
	) c
	ON (a.HADM_ID = c.HADM_ID) AND (a.SUBJECT_ID = c.SUBJECT_ID)
)
ORDER BY time

CREATE TABLE AVG_TIMED_LABEVENTS
SELECT SUBJECT_ID, HADM_ID, ITEMID, time, COUNT(VALUENUM) AS 'count', AVG(VALUENUM) AS 'average', MIN(VALUENUM) AS 'min', MAX(VALUENUM) AS 'max', VALUEUOM
FROM
TIMED_LABEVENTS
GROUP BY SUBJECT_ID, HADM_ID, ITEMID, time